# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8

install:
  - pip install tox
script:
  - tox
notifications:
  email:
    recipients:
      - somenzz@163.com
    on_success: change
    on_failure: always

